# Generated by Django 6.0 on 2025-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='El título grande (Ej: Bienvenidos)', max_length=200)),
                ('subtitulo', models.TextField(help_text='El texto pequeño de abajo')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de fondo', null=True, upload_to='portadas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Marca esta casilla si quieres que esta sea la portada actual')),
            ],
        ),
    ]
