# Generated by Django 6.0 on 2025-12-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: La Paz de Dios', max_length=200)),
                ('autora', models.CharField(help_text='Ej: Hermana María', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('video_link', models.URLField(help_text='El link del video (YouTube o Facebook)')),
                ('descripcion', models.TextField(blank=True, help_text='Breve resumen', null=True)),
            ],
        ),
    ]
