# Generated by Django 6.0 on 2026-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_devocional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pastor Juan Pérez', max_length=100)),
                ('cargo', models.CharField(help_text='Ej: Pastor Principal, Líder de Jóvenes', max_length=100)),
                ('foto', models.ImageField(help_text='Foto del líder (trata que sean cuadradas)', upload_to='lideres/')),
                ('biografia', models.TextField(blank=True, help_text='Breve descripción o versículo favorito', null=True)),
                ('orden', models.IntegerField(default=0, help_text='Número para ordenar (1 sale primero, 2 segundo, etc.)')),
            ],
            options={
                'verbose_name_plural': 'Líderes',
            },
        ),
    ]
